"use client";import {useEffect,useState} from "react";import {sb,useWs} from "@/components/useWs";
export default function B(){const ws=useWs();const [tpl,setTpl]=useState([]);const [rows,setRows]=useState([]);const [f,setF]=useState({name:"",template_name:"",tag:"",scheduled_at:""});
 const load=()=>{if(!ws)return;sb.from("templates").select("*").eq("workspace_id",ws.id).eq("status","APPROVED").then(({data})=>setTpl(data||[]));sb.from("broadcasts").select("*,messages(status)").eq("workspace_id",ws.id).order("created_at",{ascending:false}).then(({data})=>setRows(data||[]));};useEffect(load,[ws]);
 const go=async()=>{const t=tpl.find(x=>x.name===f.template_name);await fetch("/api/broadcast",{method:"POST",body:JSON.stringify({...f,workspace_id:ws.id,language:t?.language,tag:f.tag||null,scheduled_at:f.scheduled_at?new Date(f.scheduled_at).toISOString():null})});load();};
 const n=(b,s)=>b.messages.filter(m=>s.includes(m.status)).length;
 return <><h1 className="text-2xl font-bold mb-4">Broadcasts</h1>
 <div className="bg-white p-4 grid md:grid-cols-5 gap-2 mb-4"><input className="inp" placeholder="Broadcast name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className="inp" value={f.template_name} onChange={e=>setF({...f,template_name:e.target.value})}><option value="">Approved template</option>{tpl.map(t=><option key={t.id}>{t.name}</option>)}</select><input className="inp" placeholder="Tag (blank = all)" value={f.tag} onChange={e=>setF({...f,tag:e.target.value})}/><input type="datetime-local" className="inp" value={f.scheduled_at} onChange={e=>setF({...f,scheduled_at:e.target.value})}/><button className="btn" disabled={!f.template_name} onClick={go}>{f.scheduled_at?"Schedule":"Send now"}</button></div>
 <div className="overflow-x-auto bg-white"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-3">Name</th><th>Template</th><th>Status</th><th>Sent</th><th>Read</th><th>Failed</th></tr></thead><tbody>
 {rows.map(b=><tr key={b.id} className="border-b"><td className="p-3">{b.name}</td><td>{b.template_name}</td><td>{b.status}</td><td>{n(b,["sent","delivered","read"])}</td><td>{n(b,["read"])}</td><td>{n(b,["failed"])}</td></tr>)}</tbody></table></div></>;}
