"use client";import {useEffect,useState,useRef} from "react";import {sb,useWs} from "@/components/useWs";
export default function I(){const ws=useWs();const [cs,setCs]=useState([]);const [sel,setSel]=useState(null);const [msgs,setMsgs]=useState([]);const [t,setT]=useState("");const [err,setErr]=useState("");const end=useRef();
 useEffect(()=>{if(!ws)return;const l=()=>sb.from("contacts").select("*").eq("workspace_id",ws.id).not("last_inbound_at","is",null).order("last_inbound_at",{ascending:false}).then(({data})=>setCs(data||[]));l();
  const ch=sb.channel("m").on("postgres_changes",{event:"*",schema:"public",table:"messages"},()=>{l();sel&&lm(sel)}).subscribe();return()=>sb.removeChannel(ch);},[ws,sel]);
 const lm=c=>sb.from("messages").select("*").eq("contact_id",c.id).order("created_at").then(({data})=>{setMsgs(data||[]);setTimeout(()=>end.current?.scrollIntoView(),50)});
 const open=c=>{setSel(c);setErr("");lm(c)};
 const send=async()=>{const r=await(await fetch("/api/send",{method:"POST",body:JSON.stringify({workspace_id:ws.id,contact_id:sel.id,text:t})})).json();r.error?setErr(r.error):(setT(""),lm(sel));};
 const open24=sel&&Date.now()-new Date(sel.last_inbound_at)<864e5;
 return <div className="grid md:grid-cols-[300px_1fr] gap-3 h-[calc(100dvh-7rem)]">
  <aside className={`bg-white overflow-y-auto ${sel?"hidden md:block":""}`}>{cs.map(c=><button key={c.id} onClick={()=>open(c)} className={`w-full text-left p-3 border-b min-h-14 ${sel?.id===c.id?"bg-mist":""}`}><b>{c.name||c.phone}</b><div className="text-xs opacity-60">{new Date(c.last_inbound_at).toLocaleString()}</div></button>)}{!cs.length&&<p className="p-4 opacity-70">Conversations appear here when customers message you.</p>}</aside>
  {sel?<section className="bg-white flex flex-col min-h-0"><div className="p-3 border-b flex items-center gap-2"><button className="md:hidden min-h-11 min-w-11" onClick={()=>setSel(null)} aria-label="Back">‹</button><b>{sel.name||sel.phone}</b><span className={`ml-auto text-xs ${open24?"text-signal":"text-alert"}`}>{open24?"Reply window open":"Window closed, template only"}</span></div>
  <div className="flex-1 overflow-y-auto p-3 space-y-2 bg-paper">{msgs.map(m=><div key={m.id} className={`max-w-[80%] p-2 rounded-lg break-words ${m.direction==="out"?"ml-auto bg-mist":"bg-white"}`}>{m.body}<div className="text-[10px] opacity-50 text-right">{m.direction==="out"&&m.status}</div></div>)}<div ref={end}/></div>
  {err&&<p className="text-alert text-sm px-3">{err}</p>}<div className="p-2 flex gap-2 border-t" style={{paddingBottom:"calc(.5rem + env(safe-area-inset-bottom))"}}><input className="inp" disabled={!open24} value={t} onChange={e=>setT(e.target.value)} onKeyDown={e=>e.key==="Enter"&&t&&send()} placeholder="Type a reply"/><button className="btn" disabled={!t||!open24} onClick={send}>Send</button></div></section>:<section className="hidden md:grid place-items-center opacity-60">Pick a conversation</section>}</div>;}
